/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.EcommerceSales;

import Business.Business;
import Business.Order.Order;
import Business.UserAccount.UserAccount;
import javax.swing.JPanel;

/**
 *
 * @author zhaoyinhao
 */
public class EcommerceSalesMenuJPanel extends javax.swing.JPanel {

    /**
     * Creates new form EcommerceSalesMenuJPanel
     */
    UserAccount ua;
    Business business;
    JPanel CardSequencePanel;
    
    EcommerceSalesMenuJPanel(UserAccount ua, Business business, JPanel CardSequencePanel) {
        initComponents();
        this.ua = ua;
        this.business = business;
        this.CardSequencePanel = CardSequencePanel;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnOrdergoods = new javax.swing.JButton();
        btnOrderstatus = new javax.swing.JButton();

        btnOrdergoods.setText("Order Goods");
        btnOrdergoods.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdergoodsActionPerformed(evt);
            }
        });

        btnOrderstatus.setText("Order Status");
        btnOrderstatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderstatusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(btnOrdergoods, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105)
                .addComponent(btnOrderstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(121, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOrdergoods, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOrderstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(390, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnOrdergoodsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdergoodsActionPerformed
        // TODO add your handling code here:
        OrderGoodsJPanel ordergoodsarea = new OrderGoodsJPanel(ua, business, CardSequencePanel);
        CardSequencePanel.removeAll();
        CardSequencePanel.add("OrderGoodsJPanel", ordergoodsarea);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnOrdergoodsActionPerformed

    private void btnOrderstatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderstatusActionPerformed
        // TODO add your handling code here:
        OrderStatusJPanel orderstatusarea = new OrderStatusJPanel(ua, business, CardSequencePanel);
        CardSequencePanel.removeAll();
        CardSequencePanel.add("OrderStatusJPanel", orderstatusarea);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnOrderstatusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOrdergoods;
    private javax.swing.JButton btnOrderstatus;
    // End of variables declaration//GEN-END:variables
}
